### ISSUE TITLE
HXL Epic

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#1929]
This is a high level outline of incremental steps that move us toward satisfying these [user stories](https://docs.google.com/document/d/1blHsgpuB4y2pzfXEXAt0tZoMmFKJfd5dFFcQ7sphjMM/edit).  The intent is to provide input to planning discussions. 
- [x] **Refine/finalize/document the HXL libraries**
  If there is any additional work to be done on the [HXL libraries](https://github.com/HXLStandard). 
- [x] **Build an API for the HXL libraries**
  This would create a validation service that could be used by HXL or other platforms.  Could this be combined with the geomatching services described in #1928?
- [ ] **HXL data validation within HDX**
  Either as a standalone tool or as part of the HDX dataset contribute/edit workflow, allow a user to perform validations on HXL-tagged data.   Validations include data type, out-of-range (user defined ranges), place name/pcode validation (see the Geomatching tool described in #1928). 
- [ ] **HXL preview within HDX**
  HDX logic uses HXL tags to offer users a "first-cut" visualization of their data as soon as they contribute it.  Users can customize this visualization.
- [ ] **HXL integration in open-source mobile data-collection tools**
  (dpm) E.g., KoBo, ODK, Ushahidi, Magpi. (1) form designers can add HXL tags; (2) systems like KoBoCat deliver data pre-tagged; (3) "Save to HDX" - create HDX datasets from inside the tools, connecting to CKAN API. (This feature makes sense only after HDX has some of the HXL support defined in #1928).

**Comment by davidmegginson** [comment]
Converted CJ's original description into a checklist.  I think it's fair to say that libhxl and the HXL Proxy satisfy the first two steps, and that the Map Explorer may satisfy the fourth ("HXL preview within HDX").

Still TBD: KoBo (etc.) integration; validation support within HDX.
