### ISSUE TITLE
Epic: Supporting geo preview of large files

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/hdx-ckan#2631]
This epic is intended to provide the ability for us to reliably preview large shp resources.  Test cases are:

https://data.hdx.rwlabs.org/dataset/openstreetmap-shapefiles-for-gis-softwares-daily-updates (3MB zipped)
https://data.hdx.rwlabs.org/dataset/lsib-lines-global-simplified (15MB zipped). 
http://redirect.state.sbu/?url=https://data.hdx.rwlabs.org/dataset/lsib-polygons-africa-and-americas-simplified 
http://redirect.state.sbu/?url=https://data.hdx.rwlabs.org/dataset/lsib-polygons-eurasia-and-oceania-simplified 
http://redirect.state.sbu/?url=https://data.hdx.rwlabs.org/dataset/lsib-simplified-shoreline

Those resources are not currently previewing and the goal of this epic is to preview them, even on CJ's crappy internet connection at home. 

Although other ideas are welcome, on the recommendation of experts it seems the recommended approach looks something like this (likely easiest approach in blue):

![image](https://cloud.githubusercontent.com/assets/1654485/7049305/d5baf98e-de18-11e4-9a5b-8045e3d388a3.png)

This approach rests fundamentally on the vector tiles specification.  Here are some good resources, most of them from March 2015, so this is quite recent stuff. 

http://geothought.blogspot.ch/
https://www.mapbox.com/developers/vector-tiles/
https://2015.foss4g-na.org/session/state-vector-tiles
https://speakerdeck.com/hallahan/leaflet-vector-tiles

**Comment by danmihaila** [comment]
I recommend a call with @cjhendrix and me before starting this. This task has to be agile based on what we discover. I suggest:
- [ ] call about this issue - 1h
- [ ] research tools & stuff based on call - 1 day
- [ ] status research call - 2h
- [ ] installing, deploying, testing tools - 2 days [to be adjusting based on research]
- [ ] status call -1 h
  Total 3 1/2 days

**Comment by cjhendrix** [comment]
@aalecs Let me know when you want to talk about this one.  Tomorrow better than ths/fri (AM is in GVA then).

**Comment by cjhendrix** [comment]
Another interesting big of research: https://www.youtube.com/watch?v=GlTaRpg3CbQ

Pretty awesome performance on a 600 mb shapefile.

**Comment by alexandru-m-g** [comment]
1. Mali buildings:
   -  55 MB unzipped, 350k polygons
   -  pushing to PostGIS 1m 10s
   -  browser response on default zoom level 3s
   -  notes: zipped file has several layers
2. Global Simplified LSIB Lines
   - 5.8 MB unzipped, 401 lines, multi-lines 
   - pushing to PostGIS 2s
   -  browser response on default zoom level 400 ms
   - notes: problem at import because `ERROR:  Geometry type (MultiLineString) does not match column type (LineString)`
3. Africa America Simplified LSIB Lines
   -  30 MB unzipped, 125 lines, polygon, multi-polygonss
   -  pushing to PostGIS 5s
   -  browser response on default zoom level 1s
   -  notes: problem at import because `ERROR:  Geometry type (MultiPolygon) does not match column type (Polygon)`
4. North America Shorelines LSIB 
   -  16 MB unzipped, 64 k lines
   -  pushing to PostGIS 17s
   -  browser response on default zoom level 700ms
   -  notes: multiple zips in one zip

**Comment by alexandru-m-g** [comment]
Results for point geometries:

2 million points seems already a bit too much ( at least in our current configuration )
- about 8 mins to push to PostGIS
- and about 30 seconds for Chubbs to respond
- not to mention that firefox is not very responsive either in the meantime
- at zoom level 10 it starts working ok

400k is relatively decent
- less than 2 mins to push to PostGIS
- about 7 seconds for Chubbs to respond

**Comment by danmihaila** [comment]
moving it to Sprint 56 as part of the new GIS module

**Comment by alexandru-m-g** [comment]
Several notes about trying to switch to TileStache as a server: 
- it works only with the spherical mercator (900913) projection 
- so the query needs to transform the geometry to 900913. The config should be something like this:

``` json
[
"mygis": {
      "provider": {
        "class": "TileStache.Goodies.VecTiles:Provider",
        "kwargs": {
      "srid": 900913,
      "simplify": "1",
          "dbinfo": {
            "host": "db",
            "user": "postgres",
            "password": "abc",
            "database": "gis"
          },
          "queries": [
            "SELECT ST_Transform(wkb_geometry, 900913) AS __geometry__, admin0name, admin1name FROM mali"
          ]
        }
      }
    }
]
```
-  Processing the tiles is kinda slow compared to spatial server. On an 80mb shape file that was introduced in PostGis: 
  -  it takes about 1m 33s to generate a tile at zoom level 6

```
time wget http://localhost:7001/big_sm/6/46/26.json
--2015-05-26 15:20:54--  http://localhost:7001/big_sm/6/46/26.json
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:7001... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3765880 (3.6M) [application/json]
Saving to: ‘26.json’

26.json                                100%[==============================================================================>]   3.59M  --.-KB/s   in 0.007s 

2015-05-26 15:22:27 (521 MB/s) - ‘26.json’ saved [3765880/3765880]


real    1m32.938s
user    0m0.019s
sys     0m0.008s

```
-  it takes about 3m 29s to generate a tile at zoom level 3 ( the full layer ) 

```
time wget http://localhost:7001/big_sm/3/5/3.json
--2015-05-26 16:00:35--  http://localhost:7001/big_sm/3/5/3.json
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:7001... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8217794 (7.8M) [application/json]
Saving to: ‘3.json’

3.json                                 100%[==============================================================================>]   7.84M  --.-KB/s   in 0.02s  

2015-05-26 16:04:04 (387 MB/s) - ‘3.json’ saved [8217794/8217794]


real    3m28.840s
user    0m0.012s
sys     0m0.027s
```

**Comment by alexandru-m-g** [comment]
Started a document about setting up the environment: 
https://docs.google.com/document/d/1trUidBNY996wW-Qw55k1i2I5ryUz5-l4B9jTH3RgBRo

**Comment by teodorescuserban** [comment]
Awesome.
I will integrate that into our docker suite.

**Comment by cjhendrix** [comment]
We've basically done this, and we have more specific issues to address what remains to be done.  Closing this one.  Good work all!
